### ISSUE TITLE
Fehler bei Upload - Cannot assign string to property

### ISSUE THREAD

**Issue by berecont** [terminal42/contao-fineuploader#110]
Contao 4.13.43
Fine Uploader 3.4.10

Upload bricht mit Fehler ab:
```
[2024-05-06T19:53:50.271003+00:00] php.CRITICAL: Uncaught Error: Cannot assign string to property Terminal42\FineUploaderBundle\FileUpload::$maxFileSize of type int {"exception":"[object] (TypeError(code: 0): Cannot assign string to property Terminal42\\FineUploaderBundle\\FileUpload::$maxFileSize of type int at C:\\laragon\\www\\dev413\\vendor\\terminal42\\contao-fineuploader\\src\\FileUpload.php:37)"} []
[2024-05-06T19:53:50.272884+00:00] request.CRITICAL: Uncaught PHP Exception TypeError: "Cannot assign string to property Terminal42\FineUploaderBundle\FileUpload::$maxFileSize of type int" at C:\laragon\www\dev413\vendor\terminal42\contao-fineuploader\src\FileUpload.php line 37 {"exception":"[object] (TypeError(code: 0): Cannot assign string to property Terminal42\\FineUploaderBundle\\FileUpload::$maxFileSize of type int at C:\\laragon\\www\\dev413\\vendor\\terminal42\\contao-fineuploader\\src\\FileUpload.php:37)"} []
```

Anpassung FileUpload.php:
```
    public function __construct(string $name)
    {
        parent::__construct();

        $this->setName($name);

        $this->extensions = StringUtil::trimsplit(',', strtolower(Config::get('uploadTypes')));
        $this->maxFileSize = (int) Config::get('maxFileSize') ?? 0;
        $this->imageWidth = (int) Config::get('imageWidth') ?? 0;
        $this->imageHeight = (int) Config::get('imageHeight') ?? 0;
        $this->gdMaxImgWidth = (int) Config::get('gdMaxImgWidth') ?? 0;
        $this->gdMaxImgHeight = (int) Config::get('gdMaxImgHeight') ?? 0;
    }
```

» keine Fehler mehr.

**Comment by fritzmg** [comment]
It looks like there is an error in your `localconfig.php` or `config.yaml` (string instead of integer for `maxFileSize`).

**Comment by berecont** [comment]
`system/config/localconfig.php` seems to be right
```
<?php

### INSTALL SCRIPT START ###
$GLOBALS['TL_CONFIG']['licenseAccepted'] = true;
#$GLOBALS['TL_CONFIG']['adminEmail'] = 'my@domain.tld';
$GLOBALS['TL_CONFIG']['allowedAttributes'] = 'a:17:{i:0;a:2:{s:3:"key";s:1:"*";s:5:"value";s:103:"aria-*,class,data-*,dir,hidden,id,itemid,itemprop,itemref,itemscope,itemtype,lang,style,title,translate";}i:1;a:2:{s:3:"key";s:1:"a";s:5:"value";s:48:"download,href,hreflang,referrerpolicy,rel,target";}i:2;a:2:{s:3:"key";s:4:"area";s:5:"value";s:50:"alt,coords,download,href,hreflang,rel,shape,target";}i:3;a:2:{s:3:"key";s:5:"audio";s:5:"value";s:52:"autoplay,controls,crossorigin,loop,muted,preload,src";}i:4;a:2:{s:3:"key";s:3:"col";s:5:"value";s:4:"span";}i:5;a:2:{s:3:"key";s:8:"colgroup";s:5:"value";s:4:"span";}i:6;a:2:{s:3:"key";s:7:"details";s:5:"value";s:4:"open";}i:7;a:2:{s:3:"key";s:3:"img";s:5:"value";s:90:"alt,crossorigin,decoding,height,ismap,loading,referrerpolicy,sizes,src,srcset,usemap,width";}i:8;a:2:{s:3:"key";s:3:"map";s:5:"value";s:4:"name";}i:9;a:2:{s:3:"key";s:2:"ol";s:5:"value";s:19:"reversed,start,type";}i:10;a:2:{s:3:"key";s:6:"source";s:5:"value";s:27:"media,sizes,src,srcset,type";}i:11;a:2:{s:3:"key";s:5:"style";s:5:"value";s:5:"media";}i:12;a:2:{s:3:"key";s:5:"table";s:5:"value";s:43:"border,cellpadding,cellspacing,height,width";}i:13;a:2:{s:3:"key";s:2:"td";s:5:"value";s:28:"colspan,height,rowspan,width";}i:14;a:2:{s:3:"key";s:2:"th";s:5:"value";s:28:"colspan,height,rowspan,width";}i:15;a:2:{s:3:"key";s:4:"time";s:5:"value";s:8:"datetime";}i:16;a:2:{s:3:"key";s:5:"video";s:5:"value";s:97:"autoplay,controls,controlslist,crossorigin,height,loop,muted,playsinline,poster,preload,src,width";}}';
#$GLOBALS['TL_CONFIG']['gdMaxImgWidth'] = 7000;
#$GLOBALS['TL_CONFIG']['gdMaxImgHeight'] = 7000;
#$GLOBALS['TL_CONFIG']['maxFileSize'] = 10048000;
#$GLOBALS['TL_CONFIG']['imageWidth'] = 2500;
#$GLOBALS['TL_CONFIG']['imageHeight'] = 2500;
$GLOBALS['TL_CONFIG']['defaultUser'] = '';
$GLOBALS['TL_CONFIG']['defaultGroup'] = '';
$GLOBALS['TL_CONFIG']['installPassword'] = '4711';
### INSTALL SCRIPT STOP ###
```

and my `config/config.yml`, too
```
contao:
    localconfig:
        adminEmail: 'my@domain.tld'
        dateFormat: 'd.m.Y'
        datimFormat: 'd.m.Y H:i'
        timeFormat: 'H:i'
        timeZone: 'Europe/Vienna'
        resultsPerPage: '300'
        maxResultsPerPage: '500'
        gdMaxImgWidth: '7000'
        gdMaxImgHeight: '7000'
        imageWidth: '2500'
        imageHeight: '2500'
        maxFileSize: '10048000'
        backupdb_zip: true
        backupdb_var: 'just4fun'
        AutoBackupCount: 14
```
